Repository SCCapstone/CapiStonsker, pull requests merged in 2022-04, with the labels that each got.

#383 resized distance and back button
  lib/main.dart
  lib/ui/error.dart
  lib/ui/splash.dart
Labels: enhancement

#385 Nav for intent to google maps
  lib/app_nav/bottom_nav_bar.dart
  lib/app_nav/side_menu.dart
  lib/main.dart
  lib/markers/locations.dart
  lib/markers/marker_box.dart
  lib/src/map_page.dart
  lib/ui/splash.dart
  pubspec.yaml
Labels: enhancement

#386 navigation of only first eight
  lib/app_nav/bottom_nav_bar.dart
  lib/app_nav/side_menu.dart
  lib/main.dart
  lib/markers/marker_box.dart
  lib/ui/splash.dart
Labels: enhancement

#390 Duplicate friends issues
  lib/auth/fire_auth.dart
  lib/auth/log_in_page.dart
  lib/user_collections/friends_page.dart
Labels: bug

#394 Unit tests
  README.md
  lib/main.dart
  lib/markers/locations.dart
  lib/markers/marker.dart
  pubspec.yaml
  tests/firebase_friends_test.dart
  tests/firebase_marker_test.dart
  tests/loc_calcdist_test.dart
Labels: testing

#395 remove editing photo on circle
  integration_test/app_test.dart
  lib/auth/account_page.dart
  lib/generated_plugin_registrant.dart
  lib/main.dart
  lib/markers/marker_box.dart
  lib/routing/navigation_page.dart
  test_driver/test_driver.dart
Labels: bug

#400 made integration tests
  integration_test/app_test.dart
  integration_test/drawer_test.dart
  integration_test/plan_route_test.dart
  integration_test/splash_test.dart
Labels: enhancement
